version: '3'
services:
  receiver:
    image: ruby:latest
    volumes:
      - /opt/gcp/auth:/credentials
    command: >
      bash -c "[ -d fluentd-benchmark ] || git clone https://github.com/portoren/fluentd-benchmark &&
      cd fluentd-benchmark/pubsub_newrelic && bundle &&
      bundle exec fluentd -c receiver.conf"
  agent:
    image: ruby:latest
    volumes:
      - /opt/gcp/auth:/credentials
    command: >
      bash -c "[ -d fluentd-benchmark ] || git clone https://github.com/portoren/fluentd-benchmark &&
      cd fluentd-benchmark/pubsub_newrelic && bundle &&
      sed -e 's/host 127.0.0.1 \# FIX ME/host receiver/' -i agent.conf &&
      bundle exec fluentd -c agent.conf || true &
      echo Waiting for agent to come up ... &&
      while ! test -f /var/tmp/_var_log_dummy.pos ; do sleep 0.1 ; done ;
      echo Starting pushing logs .. &&
      cd fluentd-benchmark/pubsub_newrelic && bundle exec dummer -c dummer.conf -r 1000000 || true"
